import { useState, useEffect } from 'react';

const fmtQty = v => v != null ? Number(v).toLocaleString('en-IN') : '--';
const fmtPct = v => v != null ? `${Number(v).toFixed(2)}%` : '--';
const pColor = v => v == null ? 'var(--text3)' : v >= 0 ? 'var(--gain)' : 'var(--loss)';
const fmtAmt = v => v != null ? Number(v).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '--';
const PAGE_STEP = 30;

// ── Index constituent lists ─────────────────────────────────────────────────
const INDICES = {
  'Nifty 50': ['ADANIENT','ADANIPORTS','APOLLOHOSP','ASIANPAINT','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BEL','BHARTIARTL','CIPLA','COALINDIA','DRREDDY','EICHERMOT','ETERNAL','GRASIM','HCLTECH','HDFCBANK','HDFCLIFE','HINDALCO','HINDUNILVR','ICICIBANK','ITC','INFY','INDIGO','JSWSTEEL','JIOFIN','KOTAKBANK','LT','M&M','MARUTI','MAXHEALTH','NTPC','NESTLEIND','ONGC','POWERGRID','RELIANCE','SBILIFE','SHRIRAMFIN','SBIN','SUNPHARMA','TCS','TATACONSUM','TMPV','TATASTEEL','TECHM','TITAN','TRENT','ULTRACEMCO','WIPRO'],
  'Nifty Next 50': ['ABB','ADANIENSOL','ADANIGREEN','ADANIPOWER','AMBUJACEM','DMART','BAJAJHLDNG','BANKBARODA','BPCL','BOSCHLTD','BRITANNIA','CGPOWER','CANBK','CHOLAFIN','CUMMINSIND','DLF','DIVISLAB','GAIL','GODREJCP','HDFCAMC','HAL','HINDZINC','HYUNDAI','INDHOTEL','IOC','IRFC','JINDALSTEL','LTM','LODHA','MAZDOCK','MUTHOOTFIN','PIDILITIND','PFC','PNB','RECLTD','MOTHERSON','SHREECEM','ENRIN','SIEMENS','SOLARINDS','TVSMOTOR','TATACAP','TMCV','TATAPOWER','TORNTPHARM','UNIONBANK','UNITDSPR','VBL','VEDL','ZYDUSLIFE'],
  'Nifty 100': ['ABB','ADANIENSOL','ADANIENT','ADANIGREEN','ADANIPORTS','ADANIPOWER','AMBUJACEM','APOLLOHOSP','ASIANPAINT','DMART','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BAJAJHLDNG','BANKBARODA','BEL','BPCL','BHARTIARTL','BOSCHLTD','BRITANNIA','CGPOWER','CANBK','CHOLAFIN','CIPLA','COALINDIA','CUMMINSIND','DLF','DIVISLAB','DRREDDY','EICHERMOT','ETERNAL','GAIL','GODREJCP','GRASIM','HCLTECH','HDFCAMC','HDFCBANK','HDFCLIFE','HINDALCO','HAL','HINDUNILVR','HINDZINC','HYUNDAI','ICICIBANK','ITC','INDHOTEL','IOC','IRFC','INFY','INDIGO','JSWSTEEL','JINDALSTEL','JIOFIN','KOTAKBANK','LTM','LT','LODHA','M&M','MARUTI','MAXHEALTH','MAZDOCK','MUTHOOTFIN','NTPC','NESTLEIND','ONGC','PIDILITIND','PFC','POWERGRID','PNB','RECLTD','RELIANCE','SBILIFE','MOTHERSON','SHREECEM','SHRIRAMFIN','ENRIN','SIEMENS','SOLARINDS','SBIN','SUNPHARMA','TVSMOTOR','TATACAP','TCS','TATACONSUM','TMCV','TMPV','TATAPOWER','TATASTEEL','TECHM','TITAN','TORNTPHARM','TRENT','ULTRACEMCO','UNIONBANK','UNITDSPR','VBL','VEDL','WIPRO','ZYDUSLIFE'],
  'Nifty 500': ['360ONE','3MINDIA','ABB','ACC','ACMESOLAR','AIAENG','APLAPOLLO','AUBANK','AWL','AADHARHFC','AARTIIND','AAVAS','ABBOTINDIA','ACE','ACUTAAS','ADANIENSOL','ADANIENT','ADANIGREEN','ADANIPORTS','ADANIPOWER','ATGL','ABCAPITAL','ABFRL','ABLBL','ABREL','ABSLAMC','CPPLUS','AEGISLOG','AEGISVOPAK','AFCONS','AFFLE','AJANTPHARM','AKZOINDIA','ALKEM','ABDL','ARE&M','AMBER','AMBUJACEM','ANANDRATHI','ANANTRAJ','ANGELONE','ANTHEM','ANURAS','APARINDS','APOLLOHOSP','APOLLOTYRE','APTUS','ASAHIINDIA','ASHOKLEY','ASIANPAINT','ASTERDM','ASTRAL','ATHERENERG','ATUL','AUROPHARMA','AIIL','DMART','AXISBANK','BEML','BLS','BSE','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BAJAJHLDNG','BAJAJHFL','BALKRISIND','BALRAMCHIN','BANDHANBNK','BANKBARODA','BANKINDIA','MAHABANK','BATAINDIA','BAYERCROP','BELRISE','BERGEPAINT','BDL','BEL','BHARATFORG','BHEL','BPCL','BHARTIARTL','BHARTIHEXA','BIKAJI','GROWW','BIOCON','BSOFT','BLUEDART','BLUEJET','BLUESTARCO','BBTC','BOSCHLTD','FIRSTCRY','BRIGADE','BRITANNIA','MAPMYINDIA','CCL','CESC','CGPOWER','CRISIL','CANFINHOME','CANBK','CANHLIFE','CAPLIPOINT','CGCL','CARBORUNIV','CARTRADE','CASTROLIND','CEATLTD','CEMPRO','CENTRALBK','CDSL','CHALET','CHAMBLFERT','CHENNPETRO','CHOICEIN','CHOLAHLDNG','CHOLAFIN','CIPLA','CUB','CLEAN','COALINDIA','COCHINSHIP','COFORGE','COHANCE','COLPAL','CAMS','CONCORDBIO','CONCOR','COROMANDEL','CRAFTSMAN','CREDITACC','CROMPTON','CUMMINSIND','CYIENT','DCMSHRIRAM','DLF','DOMS','DABUR','DALBHARAT','DATAPATTNS','DEEPAKFERT','DEEPAKNTR','DELHIVERY','DEVYANI','DIVISLAB','DIXON','LALPATHLAB','DRREDDY','EIDPARRY','EIHOTEL','EICHERMOT','ELECON','ELGIEQUIP','EMAMILTD','EMCURE','EMMVEE','ENDURANCE','ENGINERSIN','ERIS','ESCORTS','ETERNAL','EXIDEIND','NYKAA','FEDERALBNK','FACT','FINCABLES','FSL','FIVESTAR','FORCEMOT','FORTIS','GAIL','GVT&D','GMRAIRPORT','GABRIEL','GALLANTT','GRSE','GICRE','GILLETTE','GLAND','GLAXO','GLENMARK','MEDANTA','GODIGIT','GPIL','GODFRYPHLP','GODREJCP','GODREJIND','GODREJPROP','GRANULES','GRAPHITE','GRASIM','GRAVITA','GESHIP','FLUOROCHEM','GMDCLTD','GSPL','HEG','HBLENGINE','HCLTECH','HDBFS','HDFCAMC','HDFCBANK','HDFCLIFE','HFCL','HAVELLS','HEROMOTOCO','HEXT','HSCL','HINDALCO','HAL','HINDCOPPER','HINDPETRO','HINDUNILVR','HINDZINC','POWERINDIA','HOMEFIRST','HONASA','HONAUT','HUDCO','HYUNDAI','ICICIBANK','ICICIGI','ICICIAMC','ICICIPRULI','IDBI','IDFCFIRSTB','IFCI','IIFL','IRB','IRCON','ITCHOTELS','ITC','ITI','INDGN','INDIACEM','INDIAMART','INDIANB','IEX','INDHOTEL','IOC','IOB','IRCTC','IRFC','IREDA','IGL','INDUSTOWER','INDUSINDBK','NAUKRI','INFY','INOXWIND','INTELLECT','INDIGO','IGIL','IKS','IPCALAB','JBCHEPHARM','JKCEMENT','JBMA','JKTYRE','JMFINANCIL','JSWCEMENT','JSWENERGY','JSWINFRA','JSWSTEEL','JAINREC','JPPOWER','J&KBANK','JINDALSAW','JSL','JINDALSTEL','JIOFIN','JUBLFOOD','JUBLINGREA','JUBLPHARMA','JWL','JYOTICNC','KPRMILL','KEI','KPITTECH','KAJARIACER','KPIL','KALYANKJIL','KARURVYSYA','KAYNES','KEC','KFINTECH','KIRLOSENG','KOTAKBANK','KIMS','LTF','LTTS','LGEINDIA','LICHSGFIN','LTFOODS','LTM','LT','LATENTVIEW','LAURUSLABS','THELEELA','LEMONTREE','LENSKART','LICI','LINDEINDIA','LLOYDSME','LODHA','LUPIN','MMTC','MRF','MGL','M&MFIN','M&M','MANAPPURAM','MRPL','MANKIND','MARICO','MARUTI','MFSL','MAXHEALTH','MAZDOCK','MEESHO','MINDACORP','MSUMI','MOTILALOFS','MPHASIS','MCX','MUTHOOTFIN','NATCOPHARM','NBCC','NCC','NHPC','NLCINDIA','NMDC','NSLNISP','NTPCGREEN','NTPC','NH','NATIONALUM','NAVA','NAVINFLUOR','NESTLEIND','NETWEB','NEULANDLAB','NEWGEN','NAM-INDIA','NIVABUPA','NUVAMA','NUVOCO','OBEROIRLTY','ONGC','OIL','OLAELEC','OLECTRA','PAYTM','ONESOURCE','OFSS','POLICYBZR','PCBL','PGEL','PIIND','PNBHOUSING','PTCIL','PVRINOX','PAGEIND','PARADEEP','PATANJALI','PERSISTENT','PETRONET','PFIZER','PHOENIXLTD','PWL','PIDILITIND','PINELABS','PIRAMALFIN','PPLPHARMA','POLYMED','POLYCAB','POONAWALLA','PFC','POWERGRID','PREMIERENE','PRESTIGE','PNB','RRKABEL','RBLBANK','RECLTD','RHIM','RITES','RADICO','RVNL','RAILTEL','RAINBOW','RKFORGE','REDINGTON','RELIANCE','RPOWER','SBFC','SBICARD','SBILIFE','SJVN','SRF','SAGILITY','SAILIFE','SAMMAANCAP','MOTHERSON','SAPPHIRE','SARDAEN','SAREGAMA','SCHAEFFLER','SCHNEIDER','SCI','SHREECEM','SHRIRAMFIN','SHYAMMETL','ENRIN','SIEMENS','SIGNATURE','SOBHA','SOLARINDS','SONACOMS','SONATSOFTW','STARHEALTH','SBIN','SAIL','SUMICHEM','SUNPHARMA','SUNTV','SUNDARMFIN','SUPREMEIND','SPLPETRO','SUZLON','SWANCORP','SWIGGY','SYNGENE','SYRMA','TBOTEK','TVSMOTOR','TATACAP','TATACHEM','TATACOMM','TCS','TATACONSUM','TATAELXSI','TATAINVEST','TMCV','TMPV','TATAPOWER','TATASTEEL','TATATECH','TTML','TECHM','TECHNOE','TEGA','TEJASNET','TENNIND','NIACL','RAMCOCEM','THERMAX','TIMKEN','TITAGARH','TITAN','TORNTPHARM','TORNTPOWER','TARIL','TRAVELFOOD','TRENT','TRIDENT','TRITURBINE','TIINDIA','UCOBANK','UNOMINDA','UPL','UTIAMC','ULTRACEMCO','UNIONBANK','UBL','UNITDSPR','URBANCO','USHAMART','VTL','VBL','VEDL','VIJAYA','VMM','IDEA','VOLTAS','WAAREEENER','WELCORP','WELSPUNLIV','WHIRLPOOL','WIPRO','WOCKPHARMA','YESBANK','ZFCVINDIA','ZEEL','ZENTEC','ZENSARTECH','ZYDUSLIFE','ZYDUSWELL','ECLERX'],
  'Nifty Midcap 50': ['APLAPOLLO','AUBANK','ALKEM','ASHOKLEY','AUROPHARMA','BSE','BHARATFORG','BHEL','COFORGE','COLPAL','DABUR','DIXON','NYKAA','FEDERALBNK','FORTIS','GMRAIRPORT','GODREJPROP','HAVELLS','HEROMOTOCO','HINDPETRO','ICICIGI','IDFCFIRSTB','INDUSTOWER','INDUSINDBK','NAUKRI','LAURUSLABS','LUPIN','MANKIND','MARICO','MFSL','MPHASIS','MCX','NHPC','NMDC','OIL','PAYTM','POLICYBZR','PERSISTENT','PHOENIXLTD','POLYCAB','PRESTIGE','SBICARD','SRF','SUPREMEIND','SUZLON','SWIGGY','TIINDIA','UPL','WAAREEENER','YESBANK'],
  'Nifty Midcap 100': ['360ONE','APLAPOLLO','AUBANK','ATGL','ABCAPITAL','ALKEM','ASHOKLEY','ASTRAL','AUROPHARMA','BSE','BANKINDIA','BDL','BHARATFORG','BHEL','GROWW','BIOCON','BLUESTARCO','COCHINSHIP','COFORGE','COLPAL','CONCOR','COROMANDEL','DABUR','DIXON','EXIDEIND','NYKAA','FEDERALBNK','FORTIS','GVT&D','GMRAIRPORT','GLENMARK','GODFRYPHLP','GODREJPROP','HAVELLS','HEROMOTOCO','HINDPETRO','POWERINDIA','HUDCO','ICICIGI','ICICIAMC','IDFCFIRSTB','INDIANB','IRCTC','IREDA','INDUSTOWER','INDUSINDBK','NAUKRI','JSWENERGY','JUBLFOOD','KEI','KPITTECH','KALYANKJIL','LTF','LGEINDIA','LICHSGFIN','LAURUSLABS','LENSKART','LUPIN','MRF','M&MFIN','MANKIND','MARICO','MFSL','MOTILALOFS','MPHASIS','MCX','NHPC','NMDC','NATIONALUM','OBEROIRLTY','OIL','PAYTM','OFSS','POLICYBZR','PIIND','PAGEIND','PATANJALI','PERSISTENT','PHOENIXLTD','POLYCAB','PREMIERENE','PRESTIGE','RADICO','RVNL','SBICARD','SRF','SAIL','SUPREMEIND','SUZLON','SWIGGY','TATACOMM','TATAELXSI','TATAINVEST','TIINDIA','UPL','VMM','IDEA','VOLTAS','WAAREEENER','YESBANK'],
  'Nifty Midcap 150': ['360ONE','3MINDIA','ACC','AIAENG','APLAPOLLO','AUBANK','AWL','ABBOTINDIA','ATGL','ABCAPITAL','AJANTPHARM','ALKEM','ANTHEM','APARINDS','APOLLOTYRE','ASHOKLEY','ASTRAL','AUROPHARMA','AIIL','BSE','BAJAJHFL','BALKRISIND','BANKINDIA','MAHABANK','BERGEPAINT','BDL','BHARATFORG','BHEL','BHARTIHEXA','GROWW','BIOCON','BLUESTARCO','CRISIL','COCHINSHIP','COFORGE','COLPAL','CONCOR','COROMANDEL','DABUR','DALBHARAT','DIXON','ENDURANCE','ESCORTS','EXIDEIND','NYKAA','FEDERALBNK','FORTIS','GVT&D','GMRAIRPORT','GICRE','GLAXO','GLENMARK','MEDANTA','GODFRYPHLP','GODREJIND','GODREJPROP','FLUOROCHEM','HDBFS','HAVELLS','HEROMOTOCO','HEXT','HINDPETRO','POWERINDIA','HONAUT','HUDCO','ICICIGI','ICICIAMC','ICICIPRULI','IDFCFIRSTB','ITCHOTELS','INDIANB','IRCTC','IREDA','INDUSTOWER','INDUSINDBK','NAUKRI','IPCALAB','JKCEMENT','JSWENERGY','JSWINFRA','JSL','JUBLFOOD','KPRMILL','KEI','KPITTECH','KALYANKJIL','LTF','LTTS','LGEINDIA','LICHSGFIN','LAURUSLABS','LENSKART','LICI','LINDEINDIA','LLOYDSME','LUPIN','MRF','M&MFIN','MANKIND','MARICO','MFSL','MOTILALOFS','MPHASIS','MCX','NHPC','NLCINDIA','NMDC','NTPCGREEN','NATIONALUM','NAM-INDIA','OBEROIRLTY','OIL','PAYTM','OFSS','POLICYBZR','PIIND','PAGEIND','PATANJALI','PERSISTENT','PETRONET','PHOENIXLTD','POLYCAB','PREMIERENE','PRESTIGE','RADICO','RVNL','SBICARD','SJVN','SRF','SCHAEFFLER','SAIL','SUNDARMFIN','SUPREMEIND','SUZLON','SWIGGY','TATACOMM','TATAELXSI','TATAINVEST','NIACL','THERMAX','TORNTPOWER','TIINDIA','UNOMINDA','UPL','UBL','VMM','IDEA','VOLTAS','WAAREEENER','YESBANK'],
  'Nifty Midcap Select': ['AUBANK','ASHOKLEY','AUROPHARMA','BSE','BHARATFORG','BHEL','DIXON','FORTIS','HEROMOTOCO','HINDPETRO','INDIANB','INDUSTOWER','INDUSINDBK','NAUKRI','LICI','LUPIN','MARICO','PAYTM','POLICYBZR','PERSISTENT','POLYCAB','SRF','SUZLON','SWIGGY','YESBANK'],
  'Nifty Smallcap 50': ['AEGISLOG','AFFLE','ARE&M','AMBER','ANANDRATHI','ANGELONE','ASTERDM','BANDHANBNK','CESC','CASTROLIND','CDSL','CHOLAHLDNG','CUB','COHANCE','CAMS','CROMPTON','DELHIVERY','LALPATHLAB','FIVESTAR','GLAND','HSCL','HINDCOPPER','IIFL','IGL','INOXWIND','KARURVYSYA','KAYNES','KEC','KFINTECH','MANAPPURAM','NATCOPHARM','NBCC','NH','NAVINFLUOR','NEULANDLAB','PGEL','PNBHOUSING','PIRAMALFIN','PPLPHARMA','POONAWALLA','RBLBANK','REDINGTON','RPOWER','SAILIFE','SONACOMS','SYNGENE','TATACHEM','TATATECH','WELCORP','WOCKPHARMA'],
  'Nifty Smallcap 100': ['AARTIIND','ABREL','AEGISLOG','AFCONS','AFFLE','ARE&M','AMBER','ANANDRATHI','ANANTRAJ','ANGELONE','APTUS','ASTERDM','ATHERENERG','BEML','BLS','BANDHANBNK','FIRSTCRY','BRIGADE','CESC','CGCL','CASTROLIND','CDSL','CHAMBLFERT','CHOLAHLDNG','CUB','COHANCE','CAMS','CREDITACC','CROMPTON','DATAPATTNS','DEEPAKFERT','DELHIVERY','DEVYANI','LALPATHLAB','FSL','FIVESTAR','FORCEMOT','GRSE','GLAND','GPIL','GESHIP','GMDCLTD','HBLENGINE','HSCL','HINDCOPPER','IDBI','IFCI','IIFL','IRCON','ITI','IGL','INOXWIND','IKS','JBMA','JMFINANCIL','JSWCEMENT','JYOTICNC','KARURVYSYA','KAYNES','KEC','KFINTECH','MANAPPURAM','MRPL','MEESHO','NATCOPHARM','NBCC','NH','NAVINFLUOR','NETWEB','NEULANDLAB','NUVAMA','OLAELEC','PGEL','PNBHOUSING','PWL','PINELABS','PIRAMALFIN','PPLPHARMA','POONAWALLA','RBLBANK','REDINGTON','RPOWER','SAGILITY','SAILIFE','SARDAEN','SIGNATURE','SONACOMS','STARHEALTH','SWANCORP','SYNGENE','TATACHEM','TATATECH','TENNIND','RAMCOCEM','TRITURBINE','URBANCO','WELCORP','WHIRLPOOL','WOCKPHARMA','ZENSARTECH'],
  'Nifty Smallcap 250': ['ACMESOLAR','AADHARHFC','AARTIIND','AAVAS','ACE','ACUTAAS','ABFRL','ABLBL','ABREL','ABSLAMC','CPPLUS','AEGISLOG','AEGISVOPAK','AFCONS','AFFLE','AKZOINDIA','ABDL','ARE&M','AMBER','ANANDRATHI','ANANTRAJ','ANGELONE','ANURAS','APTUS','ASAHIINDIA','ASTERDM','ATHERENERG','ATUL','BEML','BLS','BALRAMCHIN','BANDHANBNK','BATAINDIA','BAYERCROP','BELRISE','BIKAJI','BSOFT','BLUEDART','BLUEJET','BBTC','FIRSTCRY','BRIGADE','MAPMYINDIA','CCL','CESC','CANFINHOME','CANHLIFE','CAPLIPOINT','CGCL','CARBORUNIV','CARTRADE','CASTROLIND','CEATLTD','CEMPRO','CENTRALBK','CDSL','CHALET','CHAMBLFERT','CHENNPETRO','CHOICEIN','CHOLAHLDNG','CUB','CLEAN','COHANCE','CAMS','CONCORDBIO','CRAFTSMAN','CREDITACC','CROMPTON','CYIENT','DCMSHRIRAM','DOMS','DATAPATTNS','DEEPAKFERT','DEEPAKNTR','DELHIVERY','DEVYANI','LALPATHLAB','EIDPARRY','EIHOTEL','ELECON','ELGIEQUIP','EMAMILTD','EMCURE','EMMVEE','ENGINERSIN','ERIS','FACT','FINCABLES','FSL','FIVESTAR','FORCEMOT','GABRIEL','GALLANTT','GRSE','GILLETTE','GLAND','GODIGIT','GPIL','GRANULES','GRAPHITE','GRAVITA','GESHIP','GMDCLTD','GSPL','HEG','HBLENGINE','HFCL','HSCL','HINDCOPPER','HOMEFIRST','HONASA','IDBI','IFCI','IIFL','IRB','IRCON','ITI','INDGN','INDIACEM','INDIAMART','IEX','IOB','IGL','INOXWIND','INTELLECT','IGIL','IKS','JBCHEPHARM','JBMA','JKTYRE','JMFINANCIL','JSWCEMENT','JAINREC','JPPOWER','J&KBANK','JINDALSAW','JUBLINGREA','JUBLPHARMA','JWL','JYOTICNC','KAJARIACER','KPIL','KARURVYSYA','KAYNES','KEC','KFINTECH','KIRLOSENG','KIMS','LTFOODS','LATENTVIEW','THELEELA','LEMONTREE','MMTC','MGL','MANAPPURAM','MRPL','MEESHO','MINDACORP','MSUMI','NATCOPHARM','NBCC','NCC','NSLNISP','NH','NAVA','NAVINFLUOR','NETWEB','NEULANDLAB','NEWGEN','NIVABUPA','NUVAMA','NUVOCO','OLAELEC','OLECTRA','ONESOURCE','PCBL','PGEL','PNBHOUSING','PTCIL','PVRINOX','PARADEEP','PFIZER','PWL','PINELABS','PIRAMALFIN','PPLPHARMA','POLYMED','POONAWALLA','RRKABEL','RBLBANK','RHIM','RITES','RAILTEL','RAINBOW','RKFORGE','REDINGTON','RPOWER','SBFC','SAGILITY','SAILIFE','SAMMAANCAP','SAPPHIRE','SARDAEN','SAREGAMA','SCHNEIDER','SCI','SHYAMMETL','SIGNATURE','SOBHA','SONACOMS','SONATSOFTW','STARHEALTH','SUMICHEM','SUNTV','SPLPETRO','SWANCORP','SYNGENE','SYRMA','TBOTEK','TATACHEM','TATATECH','TTML','TECHNOE','TEGA','TEJASNET','TENNIND','RAMCOCEM','TIMKEN','TITAGARH','TARIL','TRAVELFOOD','TRIDENT','TRITURBINE','UCOBANK','UTIAMC','URBANCO','USHAMART','VTL','VIJAYA','WELCORP','WELSPUNLIV','WHIRLPOOL','WOCKPHARMA','ZFCVINDIA','ZEEL','ZENTEC','ZENSARTECH','ZYDUSWELL','ECLERX'],
  'Nifty Microcap 250': ['ASKAUTOLTD','AXISCADES','AARTIDRUGS','AARTIPHARM','AVL','ADVENZYMES','AEQUS','AETHER','AHLUCONT','AKUMS','APLLTD','ALIVUS','ALKYLAMINE','ALOKINDS','APOLLO','ACI','ARVINDFASN','ARVIND','ASHAPURMIN','ASHOKA','ASTRAMICRO','ATLANTAELE','AURIONPRO','AVALON','AVANTIFEED','CCAVENUE','AWFIS','AZAD','BAJAJELEC','BALAMINES','BALUFORGE','BANCOINDIA','BIRLACORPN','BBOX','BLACKBUCK','BLUESTONE','BORORENEW','CIEINDIA','CMSINFO','CORONA','CSBBANK','CAMPUS','CRAMC','CAPILLARY','CELLO','CENTURYPLY','CERA','CIGNITITEC','CRIZAC','CUPID','DCBBANK','DATAMATICS','DIACABS','DBL','AGARWALEYE','DUMMYALCAR','DYNAMATECH','EPL','EDELWEISS','EMIL','ELECTCAST','ELLEN','EMBDL','ENTERO','EIEL','EQUITASBNK','ETHOSLTD','EUREKAFORB','FEDFINA','FIEMIND','FINPIPE','UTLSOLAR','GHCL','GMMPFAUDLR','GMRP&UI','GRWRHITECH','GODREJAGRO','GOKEX','GOKULAGRO','GREAVESCOT','GAEL','GNFC','GPPL','GSFC','HGINFRA','HAPPSTMNDS','HCG','HEMIPROP','HERITGFOOD','HCC','IFBIND','IIFLCAPS','INOXINDIA','INDIAGLYCO','INDIASHLTR','IMFA','INDIGOPNTS','ICIL','INOXGREEN','IONEXCHANG','JKLAKSHMI','JKPAPER','JAIBALAJI','JAMNAAUTO','JSFB','JAYNECOIND','JSLL','JLHL','JUSTDIAL','JYOTHYLAB','KNRCON','KPIGREEN','KRBL','KRN','KSB','KANSAINER','KTKBANK','KSCL','KIRLOSBROS','KIRLPNU','KITEX','LXCHEM','IXIGO','LLOYDSENGG','LLOYDSENT','LUMAXTECH','MOIL','MSTCLTD','MTARTECH','MAHSCOOTER','MAHSEAMLES','MANORAMA','MARKSANS','MASTEK','MEDPLUS','METROPOLIS','MIDHANI','BECTORFOOD','NEOGEN','NESCO','NFL','NAZARA','NETWORK18','OPTIEMUS','ORIENTCEM','ORKLAINDIA','OSWALPUMPS','PNGJL','PCJEWELLER','PNCINFRA','PTC','PARAS','PARKHOSPS','PGIL','PICCADIL','POWERMECH','PRAJIND','PRICOLLTD','PFOCUS','PRSMJOHNSN','PRIVISCL','PRUDENT','PURVA','QPOWER','QUESS','RAIN','RALLIS','RCF','RATEGAIN','RTNINDIA','RTNPOWER','RAYMONDLSL','REDTAPE','REFEX','RELAXO','RELIGARE','RBA','ROUTE','RUBICON','SKFINDUS','SKFINDIA','SKYGOLD','SMLMAH','SAATVIKGL','SAFARI','SAMHI','SANDUMA','SANSERA','SENCO','STYL','SHAILY','SHAKTIPUMP','SHARDACROP','SHAREINDIA','SFL','SHILPAMED','RENUKA','SHRIPISTON','SKIPPER','SMARTWORKS','SOUTHBANK','LOTUSDEV','STARCEMENT','SWSOLAR','STLTECH','STAR','STYRENIX','SUBROS','SUDARSCHEM','SUDEEPPHRM','SPARC','SUNTECK','SUPRIYA','SURYAROSNI','TARC','TDPOWERSYS','TSFINV','TVSSCS','TMB','TANLA','TEXRAIL','THANGAMAYL','ANUP','THOMASCOOK','THYROCARE','TI','TIMETECHNO','TIPSMUSIC','TRANSRAILL','TRIVENI','UJJIVANSFB','VGUARD','VMART','VIPIND','V2RETAIL','WABAG','VAIBHAVGBL','DBREALTY','VARROC','MANYAVAR','VIKRAMSOLR','VIYASH','VOLTAMP','WAAREERTL','WAKEFIT','WEWORK','WEBELSOLAR','WELENT','WESTLIFE','YATHARTH','ZAGGLE'],
  'Nifty MidSmallcap 400': ['360ONE','3MINDIA','ACC','ACMESOLAR','AIAENG','APLAPOLLO','AUBANK','AWL','AADHARHFC','AARTIIND','AAVAS','ABBOTINDIA','ACE','ACUTAAS','ATGL','ABCAPITAL','ABFRL','ABLBL','ABREL','ABSLAMC','CPPLUS','AEGISLOG','AEGISVOPAK','AFCONS','AFFLE','AJANTPHARM','AKZOINDIA','ALKEM','ABDL','ARE&M','AMBER','ANANDRATHI','ANANTRAJ','ANGELONE','ANTHEM','ANURAS','APARINDS','APOLLOTYRE','APTUS','ASAHIINDIA','ASHOKLEY','ASTERDM','ASTRAL','ATHERENERG','ATUL','AUROPHARMA','AIIL','BEML','BLS','BSE','BAJAJHFL','BALKRISIND','BALRAMCHIN','BANDHANBNK','BANKINDIA','MAHABANK','BATAINDIA','BAYERCROP','BELRISE','BERGEPAINT','BDL','BHARATFORG','BHEL','BHARTIHEXA','BIKAJI','GROWW','BIOCON','BSOFT','BLUEDART','BLUEJET','BLUESTARCO','BBTC','FIRSTCRY','BRIGADE','MAPMYINDIA','CCL','CESC','CRISIL','CANFINHOME','CANHLIFE','CAPLIPOINT','CGCL','CARBORUNIV','CARTRADE','CASTROLIND','CEATLTD','CEMPRO','CENTRALBK','CDSL','CHALET','CHAMBLFERT','CHENNPETRO','CHOICEIN','CHOLAHLDNG','CUB','CLEAN','COCHINSHIP','COFORGE','COHANCE','COLPAL','CAMS','CONCORDBIO','CONCOR','COROMANDEL','CRAFTSMAN','CREDITACC','CROMPTON','CYIENT','DCMSHRIRAM','DOMS','DABUR','DALBHARAT','DATAPATTNS','DEEPAKFERT','DEEPAKNTR','DELHIVERY','DEVYANI','DIXON','LALPATHLAB','EIDPARRY','EIHOTEL','ELECON','ELGIEQUIP','EMAMILTD','EMCURE','EMMVEE','ENDURANCE','ENGINERSIN','ERIS','ESCORTS','EXIDEIND','NYKAA','FEDERALBNK','FACT','FINCABLES','FSL','FIVESTAR','FORCEMOT','FORTIS','GVT&D','GMRAIRPORT','GABRIEL','GALLANTT','GRSE','GICRE','GILLETTE','GLAND','GLAXO','GLENMARK','MEDANTA','GODIGIT','GPIL','GODFRYPHLP','GODREJIND','GODREJPROP','GRANULES','GRAPHITE','GRAVITA','GESHIP','FLUOROCHEM','GMDCLTD','GSPL','HEG','HBLENGINE','HDBFS','HFCL','HAVELLS','HEROMOTOCO','HEXT','HSCL','HINDCOPPER','HINDPETRO','POWERINDIA','HOMEFIRST','HONASA','HONAUT','HUDCO','ICICIGI','ICICIAMC','ICICIPRULI','IDBI','IDFCFIRSTB','IFCI','IIFL','IRB','IRCON','ITCHOTELS','ITI','INDGN','INDIACEM','INDIAMART','INDIANB','IEX','IOB','IRCTC','IREDA','IGL','INDUSTOWER','INDUSINDBK','NAUKRI','INOXWIND','INTELLECT','IGIL','IKS','IPCALAB','JBCHEPHARM','JKCEMENT','JBMA','JKTYRE','JMFINANCIL','JSWCEMENT','JSWENERGY','JSWINFRA','JAINREC','JPPOWER','J&KBANK','JINDALSAW','JSL','JUBLFOOD','JUBLINGREA','JUBLPHARMA','JWL','JYOTICNC','KPRMILL','KEI','KPITTECH','KAJARIACER','KPIL','KALYANKJIL','KARURVYSYA','KAYNES','KEC','KFINTECH','KIRLOSENG','KIMS','LTF','LTTS','LGEINDIA','LICHSGFIN','LTFOODS','LATENTVIEW','LAURUSLABS','THELEELA','LEMONTREE','LENSKART','LICI','LINDEINDIA','LLOYDSME','LUPIN','MMTC','MRF','MGL','M&MFIN','MANAPPURAM','MRPL','MANKIND','MARICO','MFSL','MEESHO','MINDACORP','MSUMI','MOTILALOFS','MPHASIS','MCX','NATCOPHARM','NBCC','NCC','NHPC','NLCINDIA','NMDC','NSLNISP','NTPCGREEN','NH','NATIONALUM','NAVA','NAVINFLUOR','NETWEB','NEULANDLAB','NEWGEN','NAM-INDIA','NIVABUPA','NUVAMA','NUVOCO','OBEROIRLTY','OIL','OLAELEC','OLECTRA','PAYTM','ONESOURCE','OFSS','POLICYBZR','PCBL','PGEL','PIIND','PNBHOUSING','PTCIL','PVRINOX','PAGEIND','PARADEEP','PATANJALI','PERSISTENT','PETRONET','PFIZER','PHOENIXLTD','PWL','PINELABS','PIRAMALFIN','PPLPHARMA','POLYMED','POLYCAB','POONAWALLA','PREMIERENE','PRESTIGE','RRKABEL','RBLBANK','RHIM','RITES','RADICO','RVNL','RAILTEL','RAINBOW','RKFORGE','REDINGTON','RPOWER','SBFC','SBICARD','SJVN','SRF','SAGILITY','SAILIFE','SAMMAANCAP','SAPPHIRE','SARDAEN','SAREGAMA','SCHAEFFLER','SCHNEIDER','SCI','SHYAMMETL','SIGNATURE','SOBHA','SONACOMS','SONATSOFTW','STARHEALTH','SAIL','SUMICHEM','SUNTV','SUNDARMFIN','SUPREMEIND','SPLPETRO','SUZLON','SWANCORP','SWIGGY','SYNGENE','SYRMA','TBOTEK','TATACHEM','TATACOMM','TATAELXSI','TATAINVEST','TATATECH','TTML','TECHNOE','TEGA','TEJASNET','TENNIND','NIACL','RAMCOCEM','THERMAX','TIMKEN','TITAGARH','TORNTPOWER','TARIL','TRAVELFOOD','TRIDENT','TRITURBINE','TIINDIA','UCOBANK','UNOMINDA','UPL','UTIAMC','UBL','URBANCO','USHAMART','VTL','VIJAYA','VMM','IDEA','VOLTAS','WAAREEENER','WELCORP','WELSPUNLIV','WHIRLPOOL','WOCKPHARMA','YESBANK','ZFCVINDIA','ZEEL','ZENTEC','ZENSARTECH','ZYDUSWELL','ECLERX'],
  'Nifty LargeMidcap 250': ['360ONE','3MINDIA','ABB','ACC','AIAENG','APLAPOLLO','AUBANK','AWL','ABBOTINDIA','ADANIENSOL','ADANIENT','ADANIGREEN','ADANIPORTS','ADANIPOWER','ATGL','ABCAPITAL','AJANTPHARM','ALKEM','AMBUJACEM','ANTHEM','APARINDS','APOLLOHOSP','APOLLOTYRE','ASHOKLEY','ASIANPAINT','ASTRAL','AUROPHARMA','AIIL','DMART','AXISBANK','BSE','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BAJAJHLDNG','BAJAJHFL','BALKRISIND','BANKBARODA','BANKINDIA','MAHABANK','BERGEPAINT','BDL','BEL','BHARATFORG','BHEL','BPCL','BHARTIARTL','BHARTIHEXA','GROWW','BIOCON','BLUESTARCO','BOSCHLTD','BRITANNIA','CGPOWER','CRISIL','CANBK','CHOLAFIN','CIPLA','COALINDIA','COCHINSHIP','COFORGE','COLPAL','CONCOR','COROMANDEL','CUMMINSIND','DLF','DABUR','DALBHARAT','DIVISLAB','DIXON','DRREDDY','EICHERMOT','ENDURANCE','ESCORTS','ETERNAL','EXIDEIND','NYKAA','FEDERALBNK','FORTIS','GAIL','GVT&D','GMRAIRPORT','GICRE','GLAXO','GLENMARK','MEDANTA','GODFRYPHLP','GODREJCP','GODREJIND','GODREJPROP','GRASIM','FLUOROCHEM','HCLTECH','HDBFS','HDFCAMC','HDFCBANK','HDFCLIFE','HAVELLS','HEROMOTOCO','HEXT','HINDALCO','HAL','HINDPETRO','HINDUNILVR','HINDZINC','POWERINDIA','HONAUT','HUDCO','HYUNDAI','ICICIBANK','ICICIGI','ICICIAMC','ICICIPRULI','IDFCFIRSTB','ITCHOTELS','ITC','INDIANB','INDHOTEL','IOC','IRCTC','IRFC','IREDA','INDUSTOWER','INDUSINDBK','NAUKRI','INFY','INDIGO','IPCALAB','JKCEMENT','JSWENERGY','JSWINFRA','JSWSTEEL','JSL','JINDALSTEL','JIOFIN','JUBLFOOD','KPRMILL','KEI','KPITTECH','KALYANKJIL','KOTAKBANK','LTF','LTTS','LGEINDIA','LICHSGFIN','LTM','LT','LAURUSLABS','LENSKART','LICI','LINDEINDIA','LLOYDSME','LODHA','LUPIN','MRF','M&MFIN','M&M','MANKIND','MARICO','MARUTI','MFSL','MAXHEALTH','MAZDOCK','MOTILALOFS','MPHASIS','MCX','MUTHOOTFIN','NHPC','NLCINDIA','NMDC','NTPCGREEN','NTPC','NATIONALUM','NESTLEIND','NAM-INDIA','OBEROIRLTY','ONGC','OIL','PAYTM','OFSS','POLICYBZR','PIIND','PAGEIND','PATANJALI','PERSISTENT','PETRONET','PHOENIXLTD','PIDILITIND','POLYCAB','PFC','POWERGRID','PREMIERENE','PRESTIGE','PNB','RECLTD','RADICO','RVNL','RELIANCE','SBICARD','SBILIFE','SJVN','SRF','MOTHERSON','SCHAEFFLER','SHREECEM','SHRIRAMFIN','ENRIN','SIEMENS','SOLARINDS','SBIN','SAIL','SUNPHARMA','SUNDARMFIN','SUPREMEIND','SUZLON','SWIGGY','TVSMOTOR','TATACAP','TATACOMM','TCS','TATACONSUM','TATAELXSI','TATAINVEST','TMCV','TMPV','TATAPOWER','TATASTEEL','TECHM','NIACL','THERMAX','TITAN','TORNTPHARM','TORNTPOWER','TRENT','TIINDIA','UNOMINDA','UPL','ULTRACEMCO','UNIONBANK','UBL','UNITDSPR','VBL','VEDL','VMM','IDEA','VOLTAS','WAAREEENER','WIPRO','YESBANK','ZYDUSLIFE'],
  'Nifty Total Market': ['360ONE','3MINDIA','ABB','ACC','ACMESOLAR','AIAENG','APLAPOLLO','ASKAUTOLTD','AUBANK','AWL','AXISCADES','AADHARHFC','AARTIDRUGS','AARTIIND','AARTIPHARM','AAVAS','ABBOTINDIA','ACE','ACUTAAS','ADANIENSOL','ADANIENT','ADANIGREEN','ADANIPORTS','ADANIPOWER','ATGL','ABCAPITAL','ABFRL','ABLBL','ABREL','ABSLAMC','CPPLUS','AVL','ADVENZYMES','AEGISLOG','AEGISVOPAK','AEQUS','AETHER','AFCONS','AFFLE','AHLUCONT','AJANTPHARM','AKUMS','AKZOINDIA','APLLTD','ALIVUS','ALKEM','ALKYLAMINE','ABDL','ALOKINDS','ARE&M','AMBER','AMBUJACEM','ANANDRATHI','ANANTRAJ','ANGELONE','ANTHEM','ANURAS','APARINDS','APOLLOHOSP','APOLLO','APOLLOTYRE','APTUS','ACI','ARVINDFASN','ARVIND','ASAHIINDIA','ASHAPURMIN','ASHOKLEY','ASHOKA','ASIANPAINT','ASTERDM','ASTRAMICRO','ASTRAL','ATHERENERG','ATLANTAELE','ATUL','AURIONPRO','AUROPHARMA','AIIL','AVALON','AVANTIFEED','DMART','CCAVENUE','AWFIS','AXISBANK','AZAD','BEML','BLS','BSE','BAJAJ-AUTO','BAJAJELEC','BAJFINANCE','BAJAJFINSV','BAJAJHLDNG','BAJAJHFL','BALAMINES','BALKRISIND','BALRAMCHIN','BALUFORGE','BANCOINDIA','BANDHANBNK','BANKBARODA','BANKINDIA','MAHABANK','BATAINDIA','BAYERCROP','BELRISE','BERGEPAINT','BDL','BEL','BHARATFORG','BHEL','BPCL','BHARTIARTL','BHARTIHEXA','BIKAJI','GROWW','BIOCON','BIRLACORPN','BSOFT','BBOX','BLACKBUCK','BLUEDART','BLUEJET','BLUESTARCO','BLUESTONE','BBTC','BORORENEW','BOSCHLTD','FIRSTCRY','BRIGADE','BRITANNIA','MAPMYINDIA','CCL','CESC','CGPOWER','CIEINDIA','CMSINFO','CORONA','CRISIL','CSBBANK','CAMPUS','CANFINHOME','CANBK','CANHLIFE','CRAMC','CAPILLARY','CAPLIPOINT','CGCL','CARBORUNIV','CARTRADE','CASTROLIND','CEATLTD','CELLO','CEMPRO','CENTRALBK','CDSL','CENTURYPLY','CERA','CHALET','CHAMBLFERT','CHENNPETRO','CHOICEIN','CHOLAHLDNG','CHOLAFIN','CIGNITITEC','CIPLA','CUB','CLEAN','COALINDIA','COCHINSHIP','COFORGE','COHANCE','COLPAL','CAMS','CONCORDBIO','CONCOR','COROMANDEL','CRAFTSMAN','CREDITACC','CRIZAC','CROMPTON','CUMMINSIND','CUPID','CYIENT','DCBBANK','DCMSHRIRAM','DLF','DOMS','DABUR','DALBHARAT','DATAPATTNS','DATAMATICS','DEEPAKFERT','DEEPAKNTR','DELHIVERY','DEVYANI','DIACABS','DBL','DIVISLAB','DIXON','AGARWALEYE','LALPATHLAB','DRREDDY','DUMMYALCAR','DYNAMATECH','EIDPARRY','EIHOTEL','EPL','EDELWEISS','EICHERMOT','ELECON','EMIL','ELECTCAST','ELGIEQUIP','ELLEN','EMAMILTD','EMBDL','EMCURE','EMMVEE','ENDURANCE','ENGINERSIN','ENTERO','EIEL','EQUITASBNK','ERIS','ESCORTS','ETERNAL','ETHOSLTD','EUREKAFORB','EXIDEIND','NYKAA','FEDFINA','FEDERALBNK','FACT','FIEMIND','FINCABLES','FINPIPE','FSL','FIVESTAR','FORCEMOT','FORTIS','UTLSOLAR','GAIL','GVT&D','GHCL','GMMPFAUDLR','GMRAIRPORT','GMRP&UI','GABRIEL','GALLANTT','GRSE','GRWRHITECH','GICRE','GILLETTE','GLAND','GLAXO','GLENMARK','MEDANTA','GODIGIT','GPIL','GODFRYPHLP','GODREJAGRO','GODREJCP','GODREJIND','GODREJPROP','GOKEX','GOKULAGRO','GRANULES','GRAPHITE','GRASIM','GRAVITA','GESHIP','GREAVESCOT','GAEL','FLUOROCHEM','GMDCLTD','GNFC','GPPL','GSFC','GSPL','HEG','HGINFRA','HBLENGINE','HCLTECH','HDBFS','HDFCAMC','HDFCBANK','HDFCLIFE','HFCL','HAPPSTMNDS','HAVELLS','HCG','HEMIPROP','HERITGFOOD','HEROMOTOCO','HEXT','HSCL','HINDALCO','HAL','HCC','HINDCOPPER','HINDPETRO','HINDUNILVR','HINDZINC','POWERINDIA','HOMEFIRST','HONASA','HONAUT','HUDCO','HYUNDAI','ICICIBANK','ICICIGI','ICICIAMC','ICICIPRULI','IDBI','IDFCFIRSTB','IFBIND','IFCI','IIFLCAPS','IIFL','INOXINDIA','IRB','IRCON','ITCHOTELS','ITC','ITI','INDGN','INDIACEM','INDIAGLYCO','INDIASHLTR','INDIAMART','INDIANB','IEX','INDHOTEL','IMFA','IOC','IOB','IRCTC','IRFC','IREDA','INDIGOPNTS','ICIL','IGL','INDUSTOWER','INDUSINDBK','NAUKRI','INFY','INOXGREEN','INOXWIND','INTELLECT','INDIGO','IGIL','IKS','IONEXCHANG','IPCALAB','JBCHEPHARM','JKCEMENT','JBMA','JKLAKSHMI','JKPAPER','JKTYRE','JMFINANCIL','JSWCEMENT','JSWENERGY','JSWINFRA','JSWSTEEL','JAIBALAJI','JAINREC','JPPOWER','J&KBANK','JAMNAAUTO','JSFB','JAYNECOIND','JSLL','JINDALSAW','JSL','JINDALSTEL','JIOFIN','JUBLFOOD','JUBLINGREA','JUBLPHARMA','JLHL','JWL','JUSTDIAL','JYOTHYLAB','JYOTICNC','KPRMILL','KEI','KNRCON','KPIGREEN','KPITTECH','KRBL','KRN','KSB','KAJARIACER','KPIL','KALYANKJIL','KANSAINER','KTKBANK','KARURVYSYA','KSCL','KAYNES','KEC','KFINTECH','KIRLOSBROS','KIRLOSENG','KIRLPNU','KITEX','KOTAKBANK','KIMS','LTF','LTTS','LGEINDIA','LICHSGFIN','LTFOODS','LTM','LT','LATENTVIEW','LAURUSLABS','LXCHEM','IXIGO','THELEELA','LEMONTREE','LENSKART','LICI','LINDEINDIA','LLOYDSENGG','LLOYDSENT','LLOYDSME','LODHA','LUMAXTECH','LUPIN','MMTC','MOIL','MRF','MSTCLTD','MTARTECH','MGL','MAHSCOOTER','MAHSEAMLES','M&MFIN','M&M','MANAPPURAM','MRPL','MANKIND','MANORAMA','MARICO','MARKSANS','MARUTI','MASTEK','MFSL','MAXHEALTH','MAZDOCK','MEDPLUS','MEESHO','METROPOLIS','MINDACORP','MIDHANI','MSUMI','MOTILALOFS','MPHASIS','BECTORFOOD','MCX','MUTHOOTFIN','NATCOPHARM','NBCC','NCC','NEOGEN','NESCO','NHPC','NLCINDIA','NMDC','NSLNISP','NTPCGREEN','NTPC','NH','NATIONALUM','NFL','NAVA','NAVINFLUOR','NAZARA','NESTLEIND','NETWEB','NETWORK18','NEULANDLAB','NEWGEN','NAM-INDIA','NIVABUPA','NUVAMA','NUVOCO','OBEROIRLTY','ONGC','OIL','OLAELEC','OLECTRA','PAYTM','ONESOURCE','OPTIEMUS','OFSS','ORIENTCEM','ORKLAINDIA','OSWALPUMPS','PNGJL','POLICYBZR','PCJEWELLER','PCBL','PGEL','PIIND','PNBHOUSING','PNCINFRA','PTC','PTCIL','PVRINOX','PAGEIND','PARADEEP','PARAS','PARKHOSPS','PATANJALI','PGIL','PERSISTENT','PETRONET','PFIZER','PHOENIXLTD','PWL','PICCADIL','PIDILITIND','PINELABS','PIRAMALFIN','PPLPHARMA','POLYMED','POLYCAB','POONAWALLA','PFC','POWERGRID','POWERMECH','PRAJIND','PREMIERENE','PRESTIGE','PRICOLLTD','PFOCUS','PRSMJOHNSN','PRIVISCL','PRUDENT','PNB','PURVA','QPOWER','QUESS','RRKABEL','RBLBANK','RECLTD','RHIM','RITES','RADICO','RVNL','RAILTEL','RAIN','RAINBOW','RALLIS','RKFORGE','RCF','RATEGAIN','RTNINDIA','RTNPOWER','RAYMONDLSL','REDINGTON','REDTAPE','REFEX','RELAXO','RELIANCE','RPOWER','RELIGARE','RBA','ROUTE','RUBICON','SBFC','SBICARD','SBILIFE','SJVN','SKFINDUS','SKFINDIA','SKYGOLD','SMLMAH','SRF','SAATVIKGL','SAFARI','SAGILITY','SAILIFE','SAMHI','SAMMAANCAP','MOTHERSON','SANDUMA','SANSERA','SAPPHIRE','SARDAEN','SAREGAMA','SCHAEFFLER','SCHNEIDER','SENCO','STYL','SHAILY','SHAKTIPUMP','SHARDACROP','SHAREINDIA','SFL','SHILPAMED','SCI','SHREECEM','RENUKA','SHRIRAMFIN','SHRIPISTON','SHYAMMETL','ENRIN','SIEMENS','SIGNATURE','SKIPPER','SMARTWORKS','SOBHA','SOLARINDS','SONACOMS','SONATSOFTW','SOUTHBANK','LOTUSDEV','STARCEMENT','STARHEALTH','SBIN','SAIL','SWSOLAR','STLTECH','STAR','STYRENIX','SUBROS','SUDARSCHEM','SUDEEPPHRM','SUMICHEM','SPARC','SUNPHARMA','SUNTV','SUNDARMFIN','SUNTECK','SUPREMEIND','SPLPETRO','SUPRIYA','SURYAROSNI','SUZLON','SWANCORP','SWIGGY','SYNGENE','SYRMA','TARC','TBOTEK','TDPOWERSYS','TSFINV','TVSMOTOR','TVSSCS','TMB','TANLA','TATACAP','TATACHEM','TATACOMM','TCS','TATACONSUM','TATAELXSI','TATAINVEST','TMCV','TMPV','TATAPOWER','TATASTEEL','TATATECH','TTML','TECHM','TECHNOE','TEGA','TEJASNET','TENNIND','TEXRAIL','THANGAMAYL','ANUP','NIACL','RAMCOCEM','THERMAX','THOMASCOOK','THYROCARE','TI','TIMETECHNO','TIMKEN','TIPSMUSIC','TITAGARH','TITAN','TORNTPHARM','TORNTPOWER','TARIL','TRANSRAILL','TRAVELFOOD','TRENT','TRIDENT','TRIVENI','TRITURBINE','TIINDIA','UCOBANK','UNOMINDA','UPL','UTIAMC','UJJIVANSFB','ULTRACEMCO','UNIONBANK','UBL','UNITDSPR','URBANCO','USHAMART','VGUARD','VMART','VIPIND','V2RETAIL','WABAG','VAIBHAVGBL','DBREALTY','VTL','VARROC','VBL','MANYAVAR','VEDL','VIJAYA','VIKRAMSOLR','VMM','VIYASH','IDEA','VOLTAMP','VOLTAS','WAAREEENER','WAAREERTL','WAKEFIT','WEWORK','WEBELSOLAR','WELCORP','WELENT','WELSPUNLIV','WESTLIFE','WHIRLPOOL','WIPRO','WOCKPHARMA','YATHARTH','YESBANK','ZFCVINDIA','ZAGGLE','ZEEL','ZENTEC','ZENSARTECH','ZYDUSLIFE','ZYDUSWELL','ECLERX'],
  'All Stocks': null,
};
const INDEX_GROUPS = [
  { label: 'Broad Market', items: ['Nifty 50','Nifty Next 50','Nifty 100','Nifty 500','Nifty Total Market','All Stocks'] },
  { label: 'Mid Cap', items: ['Nifty Midcap 50','Nifty Midcap 100','Nifty Midcap 150','Nifty Midcap Select'] },
  { label: 'Small Cap', items: ['Nifty Smallcap 50','Nifty Smallcap 100','Nifty Smallcap 250'] },
  { label: 'Mixed', items: ['Nifty MidSmallcap 400','Nifty LargeMidcap 250','Nifty Microcap 250'] },
];

const NAMES = {
  ADANIENT:'Adani Enterprises',ADANIPORTS:'Adani Ports',APOLLOHOSP:'Apollo Hospitals',
  ASIANPAINT:'Asian Paints',AXISBANK:'Axis Bank',BAJFINANCE:'Bajaj Finance',
  BAJAJFINSV:'Bajaj Finserv',BHARTIARTL:'Bharti Airtel',BPCL:'BPCL',
  BRITANNIA:'Britannia',CIPLA:'Cipla',COALINDIA:'Coal India',DIVISLAB:"Divi's Labs",
  DRREDDY:"Dr Reddy's",EICHERMOT:'Eicher Motors',ETERNAL:'Eternal Limited',
  GRASIM:'Grasim',HCLTECH:'HCL Technologies',HDFCBANK:'HDFC Bank',
  HDFCLIFE:'HDFC Life',HEROMOTOCO:'Hero MotoCorp',HINDALCO:'Hindalco',
  HINDUNILVR:'HUL',ICICIBANK:'ICICI Bank',INDUSINDBK:'IndusInd Bank',
  INFY:'Infosys',ITC:'ITC',JIOFIN:'Jio Financial',JSWSTEEL:'JSW Steel',
  KOTAKBANK:'Kotak Bank',LT:'L&T',LTM:'LTIMindtree',['M&M']:'Mahindra & Mahindra',
  MARUTI:'Maruti Suzuki',NESTLEIND:'Nestle India',NTPC:'NTPC',ONGC:'ONGC',
  POWERGRID:'Power Grid',RELIANCE:'Reliance Industries',SBIN:'SBI',
  SBILIFE:'SBI Life',SHRIRAMFIN:'Shriram Finance',SUNPHARMA:'Sun Pharma',
  TATACONSUM:'Tata Consumer',TATASTEEL:'Tata Steel',TCS:'TCS',
  TECHM:'Tech Mahindra',TITAN:'Titan',TRENT:'Trent',ULTRACEMCO:'UltraTech Cement',
  WIPRO:'Wipro','BAJAJ-AUTO':'Bajaj Auto',HDFCAMC:'HDFC AMC',
  NMDC:'NMDC',SAIL:'SAIL',TATAPOWER:'Tata Power',HAL:'HAL',BEL:'BEL',
  IRCTC:'IRCTC',RVNL:'RVNL',PFC:'PFC',RECLTD:'REC',CANBK:'Canara Bank',
  BANKBARODA:'Bank of Baroda',PNB:'PNB',YESBANK:'Yes Bank',VEDL:'Vedanta',
  COCHINSHIP:'Cochin Shipyard',LUPIN:'Lupin',DLF:'DLF',LODHA:'Lodha',
  CHOLAFIN:'Cholamandalam Finance',MARICO:'Marico',DABUR:'Dabur',
  GODREJCP:'Godrej Consumer',MUTHOOTFIN:'Muthoot Finance',MCX:'MCX',
  POLYCAB:'Polycab',HAVELLS:'Havells',SIEMENS:'Siemens',PIDILITIND:'Pidilite',
  PERSISTENT:'Persistent Systems',COFORGE:'Coforge',ZYDUSLIFE:'Zydus Lifesciences',
};

function symbolColor(sym) {
  const palette = ['#4A9EFF','#00C896','#A78BFA','#F59E0B','#FF4455','#FB923C','#34D399','#F472B6','#60A5FA'];
  let hash = 0;
  for (let i = 0; i < sym.length; i++) hash = (hash * 31 + sym.charCodeAt(i)) & 0xFFFFFF;
  return palette[Math.abs(hash) % palette.length];
}

function StockAvatar({ symbol }) {
  const color    = symbolColor(symbol);
  const initials = symbol.replace(/[^A-Z0-9]/g, '').slice(0, 2) || symbol.slice(0, 2);
  return (
    <div style={{
      width: 30, height: 30, borderRadius: '50%',
      background: color + '1a', border: `1.5px solid ${color}44`,
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      color, fontSize: 8, fontWeight: 800, letterSpacing: '0.03em',
      flexShrink: 0, fontFamily: 'var(--mono)',
    }}>
      {initials}
    </div>
  );
}

function TopCard({ stock }) {
  const hasLTP = stock.ltp != null;
  const name   = NAMES[stock.symbol] || stock.symbol;
  return (
    <div className="del-top-card">
      <div className="del-top-card-hdr">
        <StockAvatar symbol={stock.symbol} />
        <div className="del-top-card-info">
          <div className="del-top-card-name">{name}</div>
          {hasLTP ? (
            <div className="del-top-card-price">
              <span>{fmtAmt(stock.ltp)}</span>
              {stock.changePct != null && (
                <span style={{ color: pColor(stock.changePct), fontSize: 11, marginLeft: 6 }}>
                  {stock.changePct >= 0 ? '▲' : '▼'} {Math.abs(stock.changePct).toFixed(2)}%
                </span>
              )}
            </div>
          ) : (
            <div className="del-top-card-price">
              <span className="del-ltp-nil"><span className="del-ltp-nil-dot"/><span className="del-ltp-nil-dot"/><span className="del-ltp-nil-dot"/></span>
            </div>
          )}
        </div>
      </div>
      <div className="del-top-card-meta">
        <div className="del-top-card-row">
          <span className="del-top-card-k">Delivered</span>
          <span className="del-top-card-v" style={{ color: 'var(--gain)', fontWeight: 700 }}>{fmtPct(stock.pct)}</span>
        </div>
        <div className="del-pct-bar-wrap">
          <div className="del-pct-bar-track">
            <div className="del-pct-bar-fill" style={{ width: `${Math.min(stock.pct, 100)}%` }} />
          </div>
        </div>
        <div className="del-top-card-row" style={{ marginTop: 4 }}>
          <span className="del-top-card-k">Traded</span>
          <span className="del-top-card-v">{fmtQty(stock.traded)}</span>
        </div>
      </div>
    </div>
  );
}

export default function DeliveryPage() {
  const [data,        setData]        = useState(null);
  const [loading,     setLoading]     = useState(true);
  const [error,       setError]       = useState(null);
  const [index,       setIndex]       = useState('Nifty 50');
  const [dropOpen,    setDropOpen]    = useState(false);
  const [sortBy,      setSortBy]      = useState('delivered');
  const [sortDir,     setSortDir]     = useState('desc');
  const [visibleRows, setVisibleRows] = useState(PAGE_STEP);
  const [newRows,     setNewRows]     = useState(0);
  const [ltpLoading,  setLtpLoading]  = useState(false);
  const [ltpMsg,      setLtpMsg]      = useState(null);
  const [search,      setSearch]      = useState('');

  const fetchLTP = async () => {
    setLtpLoading(true); setLtpMsg(null);
    try {
      const r    = await fetch('/api/delivery?action=ltp');
      const json = await r.json();
      if (json.ok) {
        setLtpMsg({ ok: true, text: `LTP updated for ${json.count} stocks via ${json.source}. ${json.fetchesRemaining} fetch${json.fetchesRemaining !== 1 ? 'es' : ''} remaining today.` });
        const d = await fetch('/api/delivery').then(r => r.json());
        if (!d.empty) setData(d);
      } else if (json.reason === 'daily_limit') {
        setLtpMsg({ ok: false, text: 'Daily limit of 5 fetches reached. Resets at midnight IST.' });
      } else {
        setLtpMsg({ ok: false, text: json.error || 'LTP fetch failed.' });
      }
    } catch { setLtpMsg({ ok: false, text: 'Network error. Try again.' }); }
    setLtpLoading(false);
  };

  useEffect(() => {
    fetch('/api/delivery')
      .then(r => r.json())
      .then(d => { setData(d.empty ? null : d); setLoading(false); })
      .catch(() => { setError('Could not load delivery data.'); setLoading(false); });
  }, []);

  // Close dropdown on outside click
  useEffect(() => {
    const fn = e => { if (!e.target.closest('.del-index-picker')) setDropOpen(false); };
    document.addEventListener('mousedown', fn);
    return () => document.removeEventListener('mousedown', fn);
  }, []);

  if (loading) return <div className="del-state"><div className="del-spinner" /><span>Loading delivery data...</span></div>;
  if (error)   return <div className="del-state"><div style={{ fontSize:28,marginBottom:8 }}>⚠️</div><div style={{ fontWeight:700,marginBottom:4 }}>Could not load data</div><div style={{ fontSize:12,color:'var(--text3)' }}>{error}</div></div>;
  if (!data)   return (
    <div className="del-state">
      <div style={{ fontSize:32,marginBottom:12 }}>📦</div>
      <div style={{ fontWeight:700,fontSize:15,marginBottom:6 }}>Delivery data not yet uploaded</div>
      <div style={{ fontSize:12,color:'var(--text3)',maxWidth:320,textAlign:'center',lineHeight:1.7 }}>
        Upload the NSE MTO DAT file via the admin page to see top delivery stocks.
      </div>
    </div>
  );

  const { stocks, date, ltpUpdatedAt, fetchesRemaining, limit } = data;
  const remaining = fetchesRemaining ?? (limit ?? 5);

  const fmtDate = d => { try { return new Date(d + 'T00:00:00').toLocaleDateString('en-IN', { day:'numeric', month:'short', year:'numeric' }); } catch { return d; } };
  const fmtTime = d => { try { return new Date(d).toLocaleTimeString('en-IN', { hour:'2-digit', minute:'2-digit', hour12:true, timeZone:'Asia/Kolkata' }) + ' IST'; } catch { return null; } };

  // Apply index filter
  const constituents = INDICES[index];
  const indexFiltered = constituents == null
    ? stocks
    : constituents.length === 0
      ? stocks // empty list = show all (for indices we haven't mapped yet)
      : stocks.filter(s => constituents.includes(s.symbol));

  // Apply search
  const filtered = search.trim()
    ? indexFiltered.filter(s => s.symbol.toLowerCase().includes(search.toLowerCase()) || (NAMES[s.symbol] || '').toLowerCase().includes(search.toLowerCase()))
    : indexFiltered;

  // Sort
  const sorted = [...filtered].sort((a, b) => {
    let av = a[sortBy] ?? 0, bv = b[sortBy] ?? 0;
    return sortDir === 'desc' ? bv - av : av - bv;
  });

  const paged   = sorted.slice(0, visibleRows);
  const canLoad = visibleRows < sorted.length;

  const loadMore = () => {
    const prev = visibleRows, next = Math.min(visibleRows + PAGE_STEP, sorted.length);
    setNewRows(next - prev); setVisibleRows(next);
  };

  const handleSort = col => {
    if (sortBy === col) setSortDir(d => d === 'desc' ? 'asc' : 'desc');
    else { setSortBy(col); setSortDir('desc'); }
    setVisibleRows(PAGE_STEP); setNewRows(0);
  };

  const changeIndex = idx => { setIndex(idx); setDropOpen(false); setVisibleRows(PAGE_STEP); setNewRows(0); setSearch(''); };

  const SortBtn = ({ col, label }) => {
    const active = sortBy === col;
    return (
      <th className={`del-th del-th-sort${active ? ' del-th-active' : ''}`} onClick={() => handleSort(col)}>
        {label}{active ? (sortDir === 'desc' ? ' ▼' : ' ▲') : ''}
      </th>
    );
  };

  // Top 5 by delivery % within current index filter
  const top5 = [...indexFiltered].sort((a, b) => b.pct - a.pct).slice(0, 5);
  const showingLabel = canLoad ? `Showing ${paged.length} of ${sorted.length}` : `${sorted.length} stocks`;

  return (
    <div className="del-wrap">

      {/* HEADER */}
      <div className="del-header">
        <div className="del-header-left">
          <h1 className="del-title">Top Delivery</h1>
          {date && <span className="del-date">as on {fmtDate(date)}</span>}
        </div>
        <div className="del-header-right">
          {ltpUpdatedAt && <div className="del-ltp-badge"><span className="del-ltp-dot" />LTP {fmtTime(ltpUpdatedAt)}</div>}
          <button className="del-ltp-btn" onClick={fetchLTP} disabled={ltpLoading || remaining <= 0}>
            {ltpLoading ? <><span className="del-btn-spin" /> Fetching...</> : 'Fetch LTP'}
          </button>
          <span className="del-fetch-count" style={{ color: remaining <= 0 ? 'var(--loss)' : remaining <= 2 ? '#F59E0B' : 'var(--text3)' }}>
            {remaining ?? '--'}/{limit ?? 5} left
          </span>
        </div>
      </div>

      {ltpMsg && (
        <div className="del-ltp-msg" style={{ background: ltpMsg.ok ? 'rgba(0,200,150,.08)' : 'rgba(255,68,85,.08)', borderColor: ltpMsg.ok ? 'rgba(0,200,150,.3)' : 'rgba(255,68,85,.3)', color: ltpMsg.ok ? 'var(--gain)' : 'var(--loss)' }}>
          {ltpMsg.text}
        </div>
      )}

      {/* INDEX PICKER + SUMMARY */}
      <div className="del-controls-row">
        <div className="del-index-picker">
          <span className="del-index-label">Index:</span>
          <button className="del-index-btn" onClick={() => setDropOpen(o => !o)}>
            {index} {dropOpen ? '▲' : '▼'}
          </button>
          {dropOpen && (
            <div className="del-index-drop">
              {INDEX_GROUPS.map(group => (
                <div key={group.label}>
                  <div className="del-index-group">{group.label}</div>
                  {group.items.map(idx => (
                    <button key={idx}
                      className={`del-index-item${index === idx ? ' del-index-item-on' : ''}`}
                      onClick={() => changeIndex(idx)}>
                      {idx}
                    </button>
                  ))}
                </div>
              ))}
            </div>
          )}
        </div>
        <div className="del-summary-inline">
          <span className="del-sum-pill">{indexFiltered.length} stocks</span>
          <span className="del-sum-pill">
            Avg delivery: <strong>{(indexFiltered.reduce((s, r) => s + r.pct, 0) / (indexFiltered.length || 1)).toFixed(1)}%</strong>
          </span>
          <span className="del-sum-pill del-sum-green">
            High (&gt;75%): <strong>{indexFiltered.filter(s => s.pct >= 75).length}</strong>
          </span>
          <span className="del-sum-pill del-sum-red">
            Low (&lt;25%): <strong>{indexFiltered.filter(s => s.pct < 25).length}</strong>
          </span>
        </div>
      </div>

      {/* TOP 5 CARDS */}
      {top5.length > 0 && (
        <>
          <div className="del-section-label" style={{ marginTop: 16 }}>Top 5 by Delivery % — {index}</div>
          <div className="del-top-row">
            {top5.map((s, i) => <TopCard key={i} stock={s} />)}
          </div>
        </>
      )}

      {/* TABLE */}
      <div className="del-table-section">
        <div className="del-tabs-row">
          <div className="del-search-wrap">
            <input className="del-search" type="text" placeholder="Search symbol or company..."
              value={search} onChange={e => { setSearch(e.target.value); setVisibleRows(PAGE_STEP); setNewRows(0); }} />
          </div>
          <div className="del-table-count">{showingLabel}</div>
        </div>

        <div className="del-table-wrap">
          <table className="del-table">
            <thead>
              <tr>
                <th className="del-th del-th-left del-th-rank">#</th>
                <th className="del-th del-th-left">Stock</th>
                <SortBtn col="ltp"       label="LTP" />
                <SortBtn col="changePct" label="Change %" />
                <SortBtn col="traded"    label="Traded Qty" />
                <SortBtn col="delivered" label="Delivered Qty" />
                <SortBtn col="pct"       label="Delivery %" />
              </tr>
            </thead>
            <tbody>
              {paged.map((s, i) => {
                const isNew   = i >= (visibleRows - newRows);
                const isTop10 = i < 10;
                const name    = NAMES[s.symbol] || s.symbol;
                const barColor = s.pct >= 75 ? 'var(--gain)' : s.pct >= 50 ? 'var(--accent)' : s.pct >= 25 ? '#F59E0B' : 'var(--loss)';
                return (
                  <tr key={`${s.symbol}-${i}`} className={`del-tr${i % 2 === 1 ? ' del-tr-alt' : ''}${isNew ? ' del-tr-new' : ''}`}>
                    <td className="del-td del-td-rank" style={{ opacity: isTop10 ? 1 : 0.6 }}>{i + 1}</td>
                    <td className="del-td del-td-company">
                      <div className="del-company-cell">
                        <StockAvatar symbol={s.symbol} />
                        <div>
                          <div className="del-company-name" style={{ fontWeight: isTop10 ? 700 : 600, opacity: isTop10 ? 1 : 0.9 }}>{name}</div>
                          <div className="del-company-sym">{s.symbol}</div>
                        </div>
                      </div>
                    </td>
                    <td className="del-td del-td-num" style={{ opacity: isTop10 ? 1 : 0.85 }}>
                      {s.ltp != null ? <span className="del-ltp-price">{fmtAmt(s.ltp)}</span>
                        : <span className="del-ltp-nil"><span className="del-ltp-nil-dot"/><span className="del-ltp-nil-dot"/><span className="del-ltp-nil-dot"/></span>}
                    </td>
                    <td className="del-td del-td-num" style={{ opacity: isTop10 ? 1 : 0.85 }}>
                      {s.changePct != null
                        ? <span style={{ color: pColor(s.changePct), fontWeight: 600 }}>{s.changePct >= 0 ? '+' : ''}{s.changePct.toFixed(2)}%</span>
                        : <span className="del-ltp-nil"><span className="del-ltp-nil-dot"/><span className="del-ltp-nil-dot"/><span className="del-ltp-nil-dot"/></span>}
                    </td>
                    <td className="del-td del-td-num" style={{ opacity: isTop10 ? 1 : 0.8 }}>{fmtQty(s.traded)}</td>
                    <td className="del-td del-td-num del-td-bold" style={{ opacity: isTop10 ? 1 : 0.85 }}>{fmtQty(s.delivered)}</td>
                    <td className="del-td del-td-num">
                      <div className="del-pct-cell">
                        <span className="del-pct-val" style={{ color: barColor, fontWeight: 700, opacity: isTop10 ? 1 : 0.88 }}>{fmtPct(s.pct)}</span>
                        <div className="del-pct-bar-track del-pct-bar-track-sm">
                          <div className="del-pct-bar-fill" style={{ width: `${Math.min(s.pct, 100)}%`, background: barColor, opacity: 0.55 }} />
                        </div>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>

        {paged.length === 0 && indexFiltered.length === 0 && (
          <div className="del-empty-tab">
            No {index} stocks found in today's delivery data. They may not have traded today.
          </div>
        )}

        <div className="del-more-wrap">
          {canLoad
            ? <button className="del-more-btn" onClick={loadMore}>Load next {Math.min(PAGE_STEP, sorted.length - visibleRows)}</button>
            : <span className="del-more-status">{sorted.length} stocks loaded</span>}
        </div>
      </div>

      <div className="del-footer-note">
        Data sourced from NSE and processed for informational purposes only. This is not investment advice. Users should verify data independently.
      </div>
    </div>
  );
}
